[server]
static = "public"
debug = true
port = 8080

[server.cert]
key = "cert.key"
pem = "cert.pem"

[server.service]
base_currency = "KRW"
korea_exim_auth_key = "CtRNXmPEu3mUfNA8XqDXOHzZHlFxvWBL"

[amos]
base_url = "https://10.0.54.68:5081/service"

[amos.web_service]
id = "admin"
password = "8Z7Plc3p!!"

[amos.import_currency]
endpoint = "/updateCurrency"
base_currency = "USD"
currencies = [
    { code = "CHF", name = "Swiss Franc" },
    { code = "EUR", name = "Euro" },
    { code = "GBP", name = "British Pound" },
    { code = "JPY", name = "Japanese Yen" },
    { code = "KRW", name = "Korean Won" },
    { code = "SGD", name = "Singapore Dollar" },
    { code = "THB", name = "Thai Baht" },
    { code = "USD", name = "United States Dollar" },
]

[amos.future_flights]
endpoint = "/updateFutureFlights"