[server]
# Protocols:
# HTTP/1: 1
# HTTP/2: 2
# HTTP/3: 3
protocol = 3
port = 8080

[database]
url = "file:prisma/database.db"

[korea-exim]
host = "https://www.koreaexim.go.kr"
path = "/site/program/financial/exchangeJSON"
auth = "CtRNXmPEu3mUfNA8XqDXOHzZHlFxvWBL"

[amos]
# Environments:
# Production: 10.0.54.2
# Playground: 10.0.54.68
# Acceptance: 10.0.54.70
host = "https://10.0.54.2"
port = 5081

[amos.auth]
id = "admin"
password = "8Z7Plc3p!!"

[amos.services.import_currency]
end_point = "importCurrency"
amos_currency_code = "USD"

[amos.services.transfer_future_flights]
end_point = "transferFutureFlights"