publish_to: none
version: 0.0.1

name: app
description: none

environment:
  sdk: ^3.5.4

dependencies:
  file_picker: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  go_router: ^14.6.2
  http: ^1.2.2
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: NanumSquareNeo
      fonts:
        - asset: assets/fonts/NanumSquareNeo-aLt.ttf
          weight: 200
        - asset: assets/fonts/NanumSquareNeo-bRg.ttf
          weight: 400
        - asset: assets/fonts/NanumSquareNeo-dEb.ttf
          weight: 700