@addr=http://127.0.0.1:8080/api/amos-aim-webservice

POST {{addr}}/import-currency?date=2025-03-04

###

POST {{addr}}/transfer-future-flights?date=2025-03-11


###

POST {{addr}}/authorize
Authorization: Basic admin:8Z7Plc3p!!