@addr=http://127.0.0.1:8080/api/currency

POST {{addr}}
Content-Type: application/json

{
    "id": null,
    "code": "USD",
    "name": "United States Dollar",
    "base": 1
}

###

GET {{addr}}/e122ad84-b7e6-4a6d-9bff-8ebc29baabc6

###

PUT {{addr}}

{
    "id": "e122ad84-b7e6-4a6d-9bff-8ebc29baabc6",
    "code": "USD",
    "name": "United States Dollar",
    "base": 10
}

###

DELETE {{addr}}/e122ad84-b7e6-4a6d-9bff-8ebc29baabc6

###

GET {{addr}}