@addr=http://127.0.0.1:8080/api/currency

POST {{addr}}
Content-Type: application/json

{
    "id": null,
    "code": "USD",
    "name": "United States Dollar",
    "base": 1
}

###

GET {{addr}}/dfced9b7-9466-43b6-8ac4-7f039984653b

###

PUT {{addr}}

{
    "id": "dfced9b7-9466-43b6-8ac4-7f039984653b",
    "code": "USD",
    "name": "United States Dollar",
    "base": 10
}

###

DELETE {{addr}}/dfced9b7-9466-43b6-8ac4-7f039984653b

###

GET {{addr}}