@addr=http://127.0.0.1:8080/api/exchange-rate

POST {{addr}}
Content-Type: application/json

{
    "id": null,
    "code": "USD",
    "date": "2025-01-01",
    "rate": 1.0,
}

###

GET {{addr}}/1dac4a80-ad3c-4a8a-b4b4-f7ce058ea488

###

PUT {{addr}}

{
    "id": "1dac4a80-ad3c-4a8a-b4b4-f7ce058ea488",
    "code": "USD",
    "date": "2025-01-01",
    "rate": 1000.0,
}

###

DELETE {{addr}}/1dac4a80-ad3c-4a8a-b4b4-f7ce058ea488

###

GET {{addr}}

###

PATCH {{addr}}?date=2025-02-28

###

GET {{addr}}/data?date=2025-02-28